M48
; DRILL file {KiCad 9.0.0} date 2025-06-10T08:07:47+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-10T08:07:47+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.45Y-5.0271
T2
X5.38Y-2.555
X5.38Y-5.74
X9.78Y-2.555
X9.78Y-5.74
M30
