# Example secrets.yaml file

# Wi-Fi SSID and password
wifi_ssid: "You WiFi Name"
wifi_password: "Your Wifi Password"

# ESPrinkler keys

esprinkler_api_key: "Your API key

esprinkler_ws_username: "admin"
esprinkler_ws_password: "admin"

esprinkler_ota_password: "password"
esprinkler_ap_password: "password"
